exp:
  exp_dir: experiments
  device: cuda
  seed: 777
  use_wandb: True
  model_type: gan
  project: gan
  name: base

data:
  input_train_dir: food_data/train
  input_val_dir: food_data/test
  train_batch_size: 16
  val_batch_size: 16
  workers: 16

train:
  trainer: base_gan_trainer
  generator: base_gen
  discriminator: base_disc
  gen_optimizer: adam
  disc_optimizer: adam
  checkpoint_path: null
  val_metrics: [ "fid" ]
  start_step: 0
  steps: 300000
  log_step: 2
  checkpoint_step: 15000
  val_step: 100


generator_args:
  z_dim: 64
  hidden_dim: 1024
  blocks_num: 4

discriminator_args:
  hidden_dim: 256
  blocks_num: 3

gen_optimizer_args:
  lr: 0.001

disc_optimizer_args:
  lr: 4e-6

gen_losses:
  softplus_gen: 1.0

disc_losses:
  softplus_disc: 1.0


